spring.application.name=ms-auth
server.port=8091

# Base de datos MySQL / XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/db_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=7A3F8B2C9D1E4F6A0B5C8D2E7F3A9B4C6D1E8F2A5B7C3D9E4F6A0B1C5D8E2F
jwt.expiration=86400000